inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'db/**/*'

#turn off end of line checks, git will fix this
EndOfLine:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/models/user_test.rb'
